name: Builds

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  user-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm ci
      - name: Run build
        run: npm run build -w web-user
  dev-servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm ci
      - name: Run dev
        run: timeout 15 npm run dev
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  type-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm ci
      - name: Run dev
        run: npm run type-check
